-- Create tables
CREATE TABLE GCC.GCC_GDWS_SYS_MENU
(
  ID            NUMBER(16)                      NOT NULL,
  MENU_CODE     VARCHAR2(20 BYTE)               NOT NULL,
  PARENT_CODE   VARCHAR2(20 BYTE)               NOT NULL,
  MENU_NAME     VARCHAR2(100 BYTE),
  MENU_URL      VARCHAR2(200 BYTE),
  MENU_ICON     VARCHAR2(50 BYTE),
  STATUS        NUMBER(3)                       DEFAULT 1,
  MENU_ALTER    VARCHAR2(100 BYTE),
  MENU_ORDER    NUMBER(3),
  NOTES         VARCHAR2(100 BYTE),
  MENU_IMG      VARCHAR2(20 BYTE),
  MENU_NAME_EN  VARCHAR2(100 BYTE),
  CREATE_TIME   DATE                            DEFAULT SYSDATE
);

COMMENT ON TABLE GCC.GCC_GDWS_SYS_MENU IS '菜单维护';

COMMENT ON COLUMN GCC.GCC_GDWS_SYS_MENU.ID IS '序号';

COMMENT ON COLUMN GCC.GCC_GDWS_SYS_MENU.MENU_CODE IS '菜单代码';

COMMENT ON COLUMN GCC.GCC_GDWS_SYS_MENU.PARENT_CODE IS '菜单父亲代码';

COMMENT ON COLUMN GCC.GCC_GDWS_SYS_MENU.MENU_NAME IS '中文描述';

COMMENT ON COLUMN GCC.GCC_GDWS_SYS_MENU.MENU_URL IS '菜单URL';

COMMENT ON COLUMN GCC.GCC_GDWS_SYS_MENU.MENU_ALTER IS '菜单ALTER';

COMMENT ON COLUMN GCC.GCC_GDWS_SYS_MENU.MENU_ORDER IS '显示顺序';

COMMENT ON COLUMN GCC.GCC_GDWS_SYS_MENU.NOTES IS '备注';

COMMENT ON COLUMN GCC.GCC_GDWS_SYS_MENU.MENU_IMG IS '显示图片';

COMMENT ON COLUMN GCC.GCC_GDWS_SYS_MENU.MENU_NAME_EN IS '英文名称';

COMMENT ON COLUMN GCC.GCC_GDWS_SYS_MENU.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN GCC.GCC_GDWS_SYS_MENU.MENU_ICON IS '菜单icon';

COMMENT ON COLUMN GCC.GCC_GDWS_SYS_MENU.STATUS IS '是否禁用（1为不禁用，2为禁用）';

CREATE UNIQUE INDEX GCC.PK_GCC_GDWS_SYS_MENU ON GCC.GCC_GDWS_SYS_MENU
(ID);


CREATE INDEX GCC.IDX_GCC_GDWS_SYS_MENU_CODE ON GCC.GCC_GDWS_SYS_MENU
(MENU_CODE);


ALTER TABLE GCC.GCC_GDWS_SYS_MENU ADD (
  CONSTRAINT GCC_GDWS_SYS_MENU_PK
  PRIMARY KEY
  (ID)
  USING INDEX GCC.PK_GCC_GDWS_SYS_MENU
  ENABLE VALIDATE);

-- Create sequence
create sequence GCC.SEQ_GCC_GDWS_SYS_MENU_ID
minvalue 1
maxvalue 999999999999999999999999999
start with 1
increment by 1
cache 20;